name: Test

on:
  pull_request:
    branches:
      - '*'
  push:
    branches:
      - main
      - 'test/*'

jobs:
  Security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npx lockfile-lint --path package-lock.json --validate-https

  AVA:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: npm
      - run: npm ci
      - run: npm run ava -- --serial

  Lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: npm
      - run: npm ci
      - run: npm run lint

  Types:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: npm
      - run: npm ci
      - run: npm run build:typescript

  Build:
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: npm
      - run: npm ci
      - run: npm run build:webpack -- --json webpack-stats.json
      - name: Send webpack stats to RelativeCI
        if: matrix.os == 'ubuntu-latest'
        uses: relative-ci/agent-action@v1.1.0
        with:
          webpackStatsFile: ./webpack-stats.json
          key: ${{ secrets.RELATIVE_CI_KEY }}

  Safari:
    runs-on: macos-12
    steps:
      - uses: actions/checkout@v2
      - run: npm ci
      - run: npm run build:webpack
      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest
      - run: npm run pack:safari
